### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by andreabisello** [datakurre/robotframework-selenium2screenshots#4]
hi, 
how to install this library? 

thanks.

**Comment by emanlove** [comment]
Before installing the selenium2screenshots library you should first install [Pillow](https://pillow.readthedocs.io/en/3.3.x/) (which is the current maintained, pip-installable version of [PIL or Python Imaging Library](https://pypi.python.org/pypi/PIL)). To install Pillow try

```
pip install pillow
```

Then install robotframework-selenium2screenshots with

```
pip install robotframework-selenium2screenshots
```

**Comment by andreabisello** [comment]
very good, thanks.
